### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by meesterturner** [meesterturner/simple-photo-organiser#1]
## Todo List
- [x] If Exif date metadata doesn't exist, use the Windows file date, possibly as a checkbox option
- [ ] Option to move files rather than copy
- [ ] Precision selections down to hour, minute, second?
- [x] Changing numbering to number files per folder, and include existing-file detection on destination file names
- [ ] Numbering system customisation
